language: python
python:
  - "3.5"
cache:
  directories:
  - $HOME/virtualenv/python3.5/lib/python3.5/site-packages
before_install:
  - sudo apt-get install -y libopenmpi-dev openmpi-bin libhdf5-dev
  - travis_wait 32 ./install-torch.sh
  - pip install codecov pytest pytest-cov
install:
  - pip install -e .[hdf5] .
script:
  - mpirun pytest --cov=heat
after_success:
  - codecov
deploy:
  provider: pypi
  user: bhagemeier
  password:
    secure: YbQs8ZapvB1v4B19DoHkhWsRrhsLktKMX67ERnU9cfkoH4tBAijgu5gl2imjLPxb+tcSMtHX/qg9A4vk5dajeeNyke1Pzm+555632mG1Pc/k77DOlCT5/D/60JbQyDSXiAAJi8lhhs0TERyj/jAdFfNK104PG6ewJVs9ibbDhkPF/IdejDGb3s5EQkItSVGxyc0fq/CYC43a55wTIPb0ispL9UX9snacA3UiYem3+XtAT5s2L22MLKjwC0WgTO4lg3QQximLOOOY3vnRNXFmQCxZtDwpZtaPMTceIK3tTXgPD8jvF2Hoja55Gg312k/kDEzIb3WO5G6F8cu/wX58FTLsJ9LAKTau1D4hCMMq6uxfEuyQ0qolkaRSt0XRbYcWUv/LqRY3X72bEBRxyZJfAYhilpzK153JKxvrtmNJtyWuxbwSHQw4P3MkBLXQOYtG235S/lWs7qARi80ZFDXrBVFWSvqy3S2jQuMn1+IqbiBCxgxJpw2qTGD1UyWGHlniKW0uCQ5vpfmisRSpl+a0LD7e/RqK+FKSaMIwHpZRPFfBmAL1ww1OkBpH8H9N27fy8RV+J+iYmRONpgx90mZCdWhHyTZe51n3jEWXhbZUw/r6cgfAhL7+1HZKq059duno+xLWMnwtSBGeIID0XTVszG16jWvbd0cLw+h9r7G23rY=
  on:
    tags: true
